# Generated by Django 4.1.4 on 2023-01-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_post_type_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(blank=True, choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=8, null=True),
        ),
    ]
