# Generated by Django 4.1.4 on 2023-01-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_like_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='prompts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
