# Generated by Django 4.1.4 on 2023-01-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_space_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='space'),
        ),
    ]
